#pragma config(Sensor, dgtl1,  Up,             sensorTouch)
#pragma config(Sensor, dgtl2,  Down,           sensorTouch)
#pragma config(Sensor, dgtl3,  ShootTrigger,   sensorTouch)
#pragma config(Sensor, dgtl4,  PivotEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  FlywheelEncoder, sensorNone)
#pragma config(Sensor, dgtl8,  ZeroingLimit,   sensorTouch)
#pragma config(Motor,  port1,           Pivot,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           ShootMotor,    tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Variables //
int SetpointSelector = 1;
int TargetPose = 10;
const float QuadCountsPerSetpointStep = 7.5; //Experiment To Discover 10 Degree
const int ZeroingSpeedDown = 20;
const int FastSpeedUp = -35;
const int FastSpeedDown = 23;
const int SlowSpeedUp = -15;
const int SlowSpeedDown = 11;
const int MaxSetpoint = 8;
const int MinSetpoint = 1;

const float DelayTimeButtonDebounce = .01; //Seconds
const int SpinShootSpeed = 127;
//const float TargetFlywheelSpeed = 20; //Degrees Per Second
//const float ShootLoopTime = .05; //Seconds

// Motor Driving Loop //
task PivotControl(){
startMotor(Pivot,ZeroingSpeedDown);
while(SensorValue(ZeroingLimit)==0){
	wait(.01);
}
SensorValue(PivotEncoder) = 0;
while (true){
	TargetPose = SetpointSelector * QuadCountsPerSetpointStep - QuadCountsPerSetpointStep;
	if ((SensorValue(PivotEncoder) - TargetPose)>=5){
		startMotor(Pivot,FastSpeedDown);
		}
	if ((SensorValue(PivotEncoder) - TargetPose)<=-5){
		startMotor(Pivot,FastSpeedUp);
		}
	if ((SensorValue(PivotEncoder) - TargetPose)>.5 && SensorValue(PivotEncoder) - TargetPose <5){
		startMotor(Pivot,SlowSpeedDown);
		}
	if ((SensorValue(PivotEncoder) - TargetPose)<-.5 &&(SensorValue(PivotEncoder) - TargetPose)>-5){
		startMotor(Pivot,SlowSpeedUp);
		}
	if (SensorValue(PivotEncoder) - TargetPose<.5 && SensorValue(PivotEncoder) - TargetPose>-.5){
		stopMotor(Pivot);
		}
	if(SetpointSelector==1){
		if(SensorValue(ZeroingLimit)==0 && SensorValue(PivotEncoder)<4){
		startMotor(Pivot, 11);
		wait(.05);
	}

		if(SensorValue(ZeroingLimit) ==1){
			SensorValue(PivotEncoder) = 0;
		}
	}
}
}

// Setpoint Adjustment Logic //
task PositionLogic(){
while (true){
	if(SensorValue(Up)){
		if(SetpointSelector<=(MaxSetpoint-1)){
			SetpointSelector++;
			}
		while (SensorValue(Up)){
			wait(DelayTimeButtonDebounce);}
			}
	if(SensorValue(Down)){
		if(SetpointSelector>=(MinSetpoint+1)){
			SetpointSelector = SetpointSelector - 1;
			}
		while (SensorValue(Down)){
			wait(DelayTimeButtonDebounce);}
			}
}
}
// Shooting Speed Control Loop //
task ShootControl(){
	while(true){
		if(SensorValue(ShootTrigger)){
			startMotor(ShootMotor,SpinShootSpeed);
		}
		else if(SensorValue(ShootTrigger)==0){
			stopMotor(ShootMotor);
		}
	}
}



task main() {
	startTask(PivotControl);
	startTask(PositionLogic);
	startTask(ShootControl);
	while(true){
		wait(1);
		}
	}
