#pragma config(Sensor, dgtl1,  Up,             sensorTouch)
#pragma config(Sensor, dgtl2,  Down,           sensorTouch)
#pragma config(Sensor, dgtl3,  ShootTrigger,   sensorTouch)
#pragma config(Sensor, dgtl4,  PivotEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  FlywheelEncoder, sensorNone)
#pragma config(Sensor, dgtl8,  ZeroingLimit,   sensorTouch)
#pragma config(Motor,  port1,           Pivot,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           ShootMotor,    tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Variables //
int SetpointSelector = 1;
int TargetPose = 10;
const float QuadCountsPerSetpointStep = 7.5; //Experiment To Discover 10 Degree
const int ZeroingSpeedDown = 20;
const int FastSpeedUp = -35;
const int FastSpeedDown = 23;
const int SlowSpeedUp = -15;
const int SlowSpeedDown = 11;
const int MaxSetpoint = 8;
const int MinSetpoint = 1;
const int TriggerThresholdSetpoint1Zeroing = 4;

const float DelayTimeButtonDebounce = .01; //Seconds
const int SpinShootSpeed = 127;

// Motor Driving Loop //
task PivotControl(){
startMotor(Pivot,ZeroingSpeedDown);
while(SensorValue(ZeroingLimit)==0){
	wait(.01);
}//Initally Zero Encoder
SensorValue(PivotEncoder) = 0;
while (true){
	TargetPose = SetpointSelector * QuadCountsPerSetpointStep - QuadCountsPerSetpointStep;
	if ((SensorValue(PivotEncoder) - TargetPose)>=5){
		startMotor(Pivot,FastSpeedDown);
		} // If far away up go down fast
	if ((SensorValue(PivotEncoder) - TargetPose)<=-5){
		startMotor(Pivot,FastSpeedUp);
		}// If far away down go up fast
	if ((SensorValue(PivotEncoder) - TargetPose)>.5 && SensorValue(PivotEncoder) - TargetPose <5){
		startMotor(Pivot,SlowSpeedDown);
		}// If close down go up slow
	if ((SensorValue(PivotEncoder) - TargetPose)<-.5 &&(SensorValue(PivotEncoder) - TargetPose)>-5){
		startMotor(Pivot,SlowSpeedUp);
		}// If close up gp down slow
	if (SensorValue(PivotEncoder) - TargetPose<.5 && SensorValue(PivotEncoder) - TargetPose>-.5){
		stopMotor(Pivot);
		} //If close enough stop
	if(SetpointSelector==1){
		if(SensorValue(ZeroingLimit)==0 && SensorValue(PivotEncoder)<TriggerThresholdSetpoint1Zeroing){
		startMotor(Pivot, SlowSpeedDown);
		wait(.05); //Zero at Setpoint 1
	}

		if(SensorValue(ZeroingLimit) ==1){
			SensorValue(PivotEncoder) = 0;
		} //Constantly Zero Encoder For Accurate setpoints
	}
}
}

// Setpoint Adjustment Logic //
task PositionLogic(){
while (true){
	if(SensorValue(Up)){
		if(SetpointSelector<=(MaxSetpoint-1)){
			SetpointSelector++;
			} 
		while (SensorValue(Up)){
			wait(DelayTimeButtonDebounce);}
			} //One press = one var increase
	if(SensorValue(Down)){
		if(SetpointSelector>=(MinSetpoint+1)){
			SetpointSelector = SetpointSelector - 1;
			}
		while (SensorValue(Down)){
			wait(DelayTimeButtonDebounce);}
			}//One press = one var decrease
}
}
// Shooting Speed Control Loop //
task ShootControl(){
	while(true){
		if(SensorValue(ShootTrigger)){
			startMotor(ShootMotor,SpinShootSpeed);
		}//Shoot when limit is pressed
		else if(SensorValue(ShootTrigger)==0){
			stopMotor(ShootMotor);
		}
	}
}



task main() {
	startTask(PivotControl);
	startTask(PositionLogic);
	startTask(ShootControl);
	while(true){
		wait(1);
		}
	}
//Initilize other tasks
//Was going to put higher level flywheel logic here...